#!/usr/bin/env bash

# ======================================================================================
#
#         FILE:  install_moby_wordlist
#       AUTHOR:  Duc Mai <ducmai.network@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_moby_wordlist
#  DESCRIPTION:  Install the Moby wordlist and thesaurus into /usr/share/dict
#      CREATED:  May 04, 2023
#
# ======================================================================================


wget -O /tmp/moby_words.zip https://www.gutenberg.org/files/3201/files.zip
unzip /tmp/moby_words.zip -d /tmp/moby_words
sudo mv -v /tmp/moby_words /usr/share/dict/moby_words
sudo mv -v /usr/share/dict/moby_words/files/* /usr/share/dict/moby_words/
sudo rmdir -v /usr/share/dict/moby_words/files/
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec mv -v {} {}.utf-8.add \;
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec rename "y/A-Z/a-z/" {} \;
wget -O /tmp/mthesaur.txt https://www.gutenberg.org/files/3202/files/mthesaur.txt
sudo mv -v /tmp/mthesaur.txt /usr/share/dict/moby_words
