#!/usr/bin/bash
# shellcheck disable=SC2034

# ======================================================================================
#
#         FILE:  aliases
#       AUTHOR:  Duc Mai <ducmai.network@gmail.com>
#      COMPANY:  ---
#        USAGE:  Source this file in .bashrc
#  DESCRIPTION:  User-defined aliases
#      CREATED:  Mar 27, 2022
#
# ======================================================================================


# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                        _    _     ___    _    ____  _____ ____
#                       / \  | |   |_ _|  / \  / ___|| ____/ ___|
#                      / _ \ | |    | |  / _ \ \___ \|  _| \___ \
#                     / ___ \| |___ | | / ___ \ ___) | |___ ___) |
#                    /_/   \_\_____|___/_/   \_\____/|_____|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


##########
# LS/EXA #
##########

[[ -x "$(command -v exa)" ]] && alias ls='exa'

alias l='ls'
alias ll='exa -alhF'
alias la='ll --git'
alias tree='exa --tree --long'


#######
# GIT #
#######

alias gsh='git-sh'
alias gitsh='git-sh'
alias gst='git st'
alias gts='git st'
alias mgst='mgitstatus'
alias mgts='mgitstatus'
alias gcc='git cc'
alias gcm='git cm'
alias gca='git ca'
alias gdiff='gd'
alias gadd='ga'
alias gcl='git clone'
alias gco='git checkout'
alias gpsuh='gpush'
alias gpuhs='gpush'
alias git-sub-add='add_submodule'
alias git-sub-remove='remove_submodule'
alias git-empty-commit='git commit --no-gpg-sign --allow-empty -m "test: an empty commit"'
alias gg='git checkout main 2>/dev/null || git checkout master'


##########
# DOCKER #
##########

alias d=docker
alias dc=docker-compose
alias dcompose=docker-compose
alias dclear='log_task "Clearing docker containers ..."; \
  docker ps -a -q | xargs docker kill 2>/dev/null || \
  docker ps -a -q | xargs docker rm -f 2>/dev/null'
# dkill (kills the Docker Desktop GUI process) is macOS-specific --
# see bash/aliases.local.example


######
# CD #
######

alias ..='cd ..'
alias ....='cd ../..'
alias cd..='cd ..'
alias cd....='cd ../..'
alias W='cd "${HOME}"/my-site'
alias V='cd "${DOTVIM}"'
alias F='cd "${DOTFILES}"'
# cc (a machine-specific WSL shortcut) moved to bash/aliases.local.example


########
# FILE #
########

alias bashrc='vim "${DOTFILES}"/bash/bashrc'
alias pathrc='vim "${DOTFILES}"/bash/pathrc'
alias vimrc='vim "${DOTVIM}"/vimrc'
alias gitconf='vim "${DOTFILES}"/git/gitconfig'
alias func='vim "${DOTFILES}"/bash/functions'
alias bootstrap='vim "${DOTFILES}"/install/bootstrap'
alias aliasconf='vim "${DOTFILES}"/bash/aliases'
alias wiki='vim "${HOME}"/vimwiki/index.wiki'


######
# VI #
######

alias e='vim -o'
alias E='vim -o'
alias vim='vim -o'
alias vi='e3vi' # Miminal vim


########
# VIEW #
########

alias view='xdg-open'
alias open='view'
alias o='open'
alias e3='e3vi'


#######
# BIN #
#######

[[ -x "$(command -v batcat)" ]] && alias bat='batcat'
[[ -x "$(command -v lolcat)" ]] && alias cat='lolcat'
[[ -x "$(command -v trash)" ]] && alias rm='trash'
[[ -x "$(command -v ncal)" ]] && alias cal='ncal'


########
# MISC #
########

alias gbm='git-branch-manager'


#############
# SHORTHAND #
#############

alias py='python3'
alias ex='exit'
alias ttime='get_time'
alias s='source "${HOME}"/.bashrc'
alias hugolive='serve_hugo_site'
alias doctoc='doctoc --title "# Table of Contents"'
alias hugodeploy='[[ -f ".hugo_build.lock" ]] \
  && git_publish "$(pwd)" "Deploy website" doctoc \
  || log_error "Not in the root of a Hugo project"'
alias weblive='cd "${HOME}"/my-site && serve_hugo_site'
alias webdeploy='git_publish "${HOME}/my-site" "Deploy website" doctoc'
alias wikipush='git_publish "${HOME}/vimwiki" "Update wiki"'


#############
# EXPANSION #
#############

alias dday='date +%d-%m-%Y'
alias toilet='toilet -t -f mono12 --filter border:metal -F metal'
alias toiletgay='toilet --filter border:gay -F gay'
alias sqlformat='sqlformat -s --reindent --keywords upper --identifiers lower'
alias pip-install='pip install --upgrade --user'
alias pip-update='pip-review --local --auto'
alias updatedb='sudo updatedb'
alias grip='sudo grip --browser'
[[ -x "$(command -v figlet)" ]] && [[ -x "$(command -v lolcat)" ]] \
  && alias pwd='pwd | figlet -f mnemonic | lolcat'
alias show-services='systemctl list-unit-files --type=service'
