name: 🐍 Python Codestyle

on:
  workflow_call:
    inputs:
      path:
        description: "Path to lint with flake8"
        required: false
        type: string
        default: "."
      python-version:
        description: "Python version to run flake8 under"
        required: false
        type: string
        default: "3.14"
  push:

permissions:
  contents: read

jobs:
  lint:
    name: Run py-codestyle check
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🐍 Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python-version || '3.14' }}

      - name: 📥 Install Checking Modules
        run: |
          pip install --upgrade pep8-naming flake8 \
            flake8-broken-line flake8-bugbear flake8-multiline-containers \
            flake8-tidy-imports flake8-pytest-style flake8-variables-names \
            flake8-comprehensions

      - name: ✔️ Run Codestyle
        env:
          LINT_PATH: ${{ inputs.path || '.' }}
        run: flake8 "${LINT_PATH}"
