name: 📥 Sync submodules

on:
  workflow_call:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

concurrency:
  group: sync-submodules-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    name: ⤵️ Sync Submodules
    runs-on: ubuntu-latest
    steps:
      - name: ➡️ Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: ⬇️ Pull Submodules Recursively
        shell: bash
        run: |
          git submodule update --init --recursive --remote

      - name: ⬆️ Push Changes (if any)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: sync submodules" || true
          git push origin master
